security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Hiérarchie des rôles
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_CLIENT]
        ROLE_USER: [ROLE_CLIENT]

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: adresseMail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: app_home
                username_parameter: _username
                password_parameter: _password
                enable_csrf: true
            logout:
                path: app_logout
                target: app_home

    access_control:
        # Routes publiques (pas de restriction)
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/utilisateur/new, roles: PUBLIC_ACCESS }
        - { path: ^/catalogue, roles: PUBLIC_ACCESS }
        
        # Routes pour les clients connectés
        - { path: ^/panier, roles: ROLE_CLIENT }
        - { path: ^/commande, roles: ROLE_CLIENT }
        - { path: ^/utilisateur, roles: ROLE_CLIENT }
        - { path: ^/category, roles: ROLE_CLIENT }
        - { path: ^/produit, roles: ROLE_CLIENT }
        - { path: ^/tag, roles: ROLE_CLIENT }
        
        # Routes pour les administrateurs
        - { path: ^/admin, roles: ROLE_ADMIN }
        

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
